version: '3.9'
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/promtheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "9999:3000"
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"