global:
  external_labels:
    monitor: test-monitor
  scrape_interval: 5s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: service3
    static_configs:
      - targets:
          - "localhost:9464"
